name: Build, Analyze, Scan the Code

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    runs-on: Eks githubactions-eks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify runner
        run: echo "Self-hosted Runner Working"

      - name: Install dependencies
        run: npm install

      - name: Trivy file scan
        run: trivy fs . > trivyfs.txt

      # ✅ Fix starts here
      - name: Docker Login (Non-interactive)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t tic-tac-toe .

      - name: Tag Image
        run: docker tag tic-tac-toe chrajkumar22/tic-tac-toe:latest

      - name: Push Docker Image
        run: docker push chrajkumar22/tic-tac-toe:latest
