name: Build, Analyze, Scan the Code

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    runs-on: Eks githubactions-eks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify runner
        run: echo "GitHub Hosted Runner Working"

      - name: npm install dependency
        run: npm install

      - name: trivy file scan
        run: trivy fs . > trivyfs.txt

      - name: docker build and push
        run: |
           docker build -t tic-tac-toe .
           docker tag tic-tac-toe chrajkumar22/tic-tac-toe:latest
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker push chrajkumar22/tic-tac-toe:latest
        env:
          DOCKER_CLI_ACI: 1
           
